/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { JSX } from "react";

type GLTFResult = GLTF & {
  nodes: {
    Object_3: THREE.Mesh;
    Object_4: THREE.Mesh;
    Object_5: THREE.Mesh;
    Object_6: THREE.Mesh;
    Object_7: THREE.Mesh;
    Object_3001: THREE.Mesh;
    Object_4001: THREE.Mesh;
    Object_5001: THREE.Mesh;
    Object_6001: THREE.Mesh;
    Object_7001: THREE.Mesh;
  };
  materials: {
    Boutons: THREE.MeshPhysicalMaterial;
    Electronic: THREE.MeshPhysicalMaterial;
    Mesh: THREE.MeshStandardMaterial;
    Screen: THREE.MeshStandardMaterial;
    Tour: THREE.MeshStandardMaterial;
    ["Boutons.001"]: THREE.MeshPhysicalMaterial;
    ["Electronic.001"]: THREE.MeshPhysicalMaterial;
    ["Mesh.001"]: THREE.MeshStandardMaterial;
    ["Screen.001"]: THREE.MeshStandardMaterial;
    ["Tour.001"]: THREE.MeshStandardMaterial;
  };
};

export default function ColumnSpeaker(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/columnspeaker/models/scene.glb",
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null} scale={0.003}>
      <group name="Scene">
        <mesh
          name="Object_3"
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials.Boutons}
        />
        <mesh
          name="Object_4"
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.Electronic}
        />
        <mesh
          name="Object_5"
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials.Mesh}
        />
        <mesh
          name="Object_6"
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials.Screen}
        />
        <mesh
          name="Object_7"
          castShadow
          receiveShadow
          geometry={nodes.Object_7.geometry}
          material={materials.Tour}
        />
        <mesh
          name="Object_3001"
          castShadow
          receiveShadow
          geometry={nodes.Object_3001.geometry}
          material={materials["Boutons.001"]}
        />
        <mesh
          name="Object_4001"
          castShadow
          receiveShadow
          geometry={nodes.Object_4001.geometry}
          material={materials["Electronic.001"]}
        />
        <mesh
          name="Object_5001"
          castShadow
          receiveShadow
          geometry={nodes.Object_5001.geometry}
          material={materials["Mesh.001"]}
        />
        <mesh
          name="Object_6001"
          castShadow
          receiveShadow
          geometry={nodes.Object_6001.geometry}
          material={materials["Screen.001"]}
        />
        <mesh
          name="Object_7001"
          castShadow
          receiveShadow
          geometry={nodes.Object_7001.geometry}
          material={materials["Tour.001"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/columnspeaker/models/scene.glb");
