/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: radioape (https://sketchfab.com/radioape)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lowpoly-audio-speaker-06d97e02d50a41d397853d729a60bdbc
Title: Lowpoly audio speaker
*/

import * as THREE from "three";
import { JSX } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Cube__0: THREE.Mesh;
  };
  materials: {
    ["Scene_-_Root"]: THREE.MeshStandardMaterial;
  };
};

export default function DelaySpeaker(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/delayspeaker/models/scene.gltf",
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group>
        <group
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          userData={{ name: "Sketchfab_model" }}
        >
          <group
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
            userData={{ name: "931b39abec8e4ea88e8c34a73d5c6bcb.fbx" }}
          >
            <group userData={{ name: "RootNode" }}>
              <group userData={{ name: "Cube" }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube__0.geometry}
                  material={materials["Scene_-_Root"]}
                  userData={{ name: "Cube__0" }}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/delayspeaker/models/scene.gltf");
