/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: cabriocat (https://sketchfab.com/cabriocatartist)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pa-concert-speaker-clean-b6d18dc5a9ae49aa872b5d2af72da659
Title: PA concert speaker - clean
*/

import * as THREE from "three";
import { useRef, JSX } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh;
    Object_3: THREE.Mesh;
    Object_4: THREE.Mesh;
    Object_5: THREE.Mesh;
  };
  materials: {
    speaker_foam: THREE.MeshStandardMaterial;
    speaker_main: THREE.MeshStandardMaterial;
    speaker_plates: THREE.MeshStandardMaterial;
    speaker_shiny: THREE.MeshStandardMaterial;
  };
};

export default function FrontFill(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/front/models/scene.gltf",
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, -0.628]}>
          <group name="speakerobjcleanermaterialmergergles">
            <mesh
              name="Object_2"
              castShadow
              receiveShadow
              geometry={nodes.Object_2.geometry}
              material={materials.speaker_foam}
            />
            <mesh
              name="Object_3"
              castShadow
              receiveShadow
              geometry={nodes.Object_3.geometry}
              material={materials.speaker_main}
            />
            <mesh
              name="Object_4"
              castShadow
              receiveShadow
              geometry={nodes.Object_4.geometry}
              material={materials.speaker_plates}
            />
            <mesh
              name="Object_5"
              castShadow
              receiveShadow
              geometry={nodes.Object_5.geometry}
              material={materials.speaker_shiny}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/front/models/scene.gltf");
