/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Wilmer.Jose.Saumeth.Suarez (https://sketchfab.com/Wilmer.Jose.Saumeth.Suarez)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/line-array-cc558455c6d141ccb69c23222af46c8a
Title: Line Array
*/

import * as THREE from "three";
import React, { useRef, JSX } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Material2: THREE.Mesh;
    Material2_1: THREE.Mesh;
    Material4: THREE.Mesh;
    Material5: THREE.Mesh;
    Material3: THREE.Mesh;
    Material3_1: THREE.Mesh;
    Material3_2: THREE.Mesh;
    Material3_3: THREE.Mesh;
    Material3_4: THREE.Mesh;
    Material2_2: THREE.Mesh;
    Material2_3: THREE.Mesh;
    Material3_5: THREE.Mesh;
    Material3_6: THREE.Mesh;
    Material3_7: THREE.Mesh;
    Material3_8: THREE.Mesh;
    Material3_9: THREE.Mesh;
    Material2_4: THREE.Mesh;
  };
  materials: {
    material: THREE.MeshStandardMaterial;
    material_0: THREE.MeshStandardMaterial;
    material_1: THREE.MeshStandardMaterial;
    material_2: THREE.MeshStandardMaterial;
    material_3: THREE.MeshStandardMaterial;
    material_4: THREE.MeshStandardMaterial;
    material_5: THREE.MeshStandardMaterial;
    material_6: THREE.MeshStandardMaterial;
    material_7: THREE.MeshStandardMaterial;
    material_8: THREE.MeshStandardMaterial;
    material_10: THREE.MeshStandardMaterial;
    material_11: THREE.MeshStandardMaterial;
    material_9: THREE.MeshStandardMaterial;
    material_12: THREE.MeshStandardMaterial;
    material_13: THREE.MeshStandardMaterial;
    material_14: THREE.MeshStandardMaterial;
    material_15: THREE.MeshStandardMaterial;
  };
};

export default function LineArray(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/linearray/models/scene.gltf",
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null} scale={0.04}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Collada_visual_scene_group">
            <mesh
              name="Material2"
              castShadow
              receiveShadow
              geometry={nodes.Material2.geometry}
              material={materials.material}
            />
            <mesh
              name="Material2_1"
              castShadow
              receiveShadow
              geometry={nodes.Material2_1.geometry}
              material={materials.material_0}
            />
            <mesh
              name="Material4"
              castShadow
              receiveShadow
              geometry={nodes.Material4.geometry}
              material={materials.material_1}
            />
            <mesh
              name="Material5"
              castShadow
              receiveShadow
              geometry={nodes.Material5.geometry}
              material={materials.material_2}
            />
            <mesh
              name="Material3"
              castShadow
              receiveShadow
              geometry={nodes.Material3.geometry}
              material={materials.material_3}
            />
            <mesh
              name="Material3_1"
              castShadow
              receiveShadow
              geometry={nodes.Material3_1.geometry}
              material={materials.material_4}
            />
            <mesh
              name="Material3_2"
              castShadow
              receiveShadow
              geometry={nodes.Material3_2.geometry}
              material={materials.material_5}
            />
            <mesh
              name="Material3_3"
              castShadow
              receiveShadow
              geometry={nodes.Material3_3.geometry}
              material={materials.material_6}
            />
            <mesh
              name="Material3_4"
              castShadow
              receiveShadow
              geometry={nodes.Material3_4.geometry}
              material={materials.material_7}
            />
            <mesh
              name="Material2_2"
              castShadow
              receiveShadow
              geometry={nodes.Material2_2.geometry}
              material={materials.material_8}
            />
            <mesh
              name="Material2_3"
              castShadow
              receiveShadow
              geometry={nodes.Material2_3.geometry}
              material={materials.material_10}
            />
            <mesh
              name="Material3_5"
              castShadow
              receiveShadow
              geometry={nodes.Material3_5.geometry}
              material={materials.material_11}
            />
            <mesh
              name="Material3_6"
              castShadow
              receiveShadow
              geometry={nodes.Material3_6.geometry}
              material={materials.material_9}
            />
            <mesh
              name="Material3_7"
              castShadow
              receiveShadow
              geometry={nodes.Material3_7.geometry}
              material={materials.material_12}
            />
            <mesh
              name="Material3_8"
              castShadow
              receiveShadow
              geometry={nodes.Material3_8.geometry}
              material={materials.material_13}
            />
            <mesh
              name="Material3_9"
              castShadow
              receiveShadow
              geometry={nodes.Material3_9.geometry}
              material={materials.material_14}
            />
            <mesh
              name="Material2_4"
              castShadow
              receiveShadow
              geometry={nodes.Material2_4.geometry}
              material={materials.material_15}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/linearray/models/scene.gltf");
