/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Saandy (https://sketchfab.com/Saandy)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/monitor-speaker-a8dd30124e9d4c32a77fc5c4b8c689bd
Title: Monitor Speaker
*/

import * as THREE from "three";
import React, { JSX, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    monitor_speaker_lp_lambert2_0: THREE.Mesh;
  };
  materials: {
    lambert2: THREE.MeshStandardMaterial;
  };
};

export default function StageMonitor(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/stagemonitor/models/scene.gltf",
  ) as unknown as GLTFResult;

  return (
    <group {...props} dispose={null} scale={10}>
      {" "}
      {/* Add temporary large scale */}
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, Math.PI]}>
          <group
            name="monitor_speakerfbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.145}
          >
            <group name="RootNode">
              <group name="monitor_speaker_lp" scale={0.394}>
                <mesh
                  name="monitor_speaker_lp_lambert2_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.monitor_speaker_lp_lambert2_0.geometry}
                  material={materials.lambert2}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/stagemonitor/models/scene.gltf");
