/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Saandy (https://sketchfab.com/Saandy)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/monitor-speaker-a8dd30124e9d4c32a77fc5c4b8c689bd
Title: Monitor Speaker
*/

import * as THREE from "three";
import { JSX, useLayoutEffect } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    monitor_speaker_lp_lambert2_0: THREE.Mesh;
  };
  materials: {
    lambert2: THREE.MeshStandardMaterial;
  };
};

export default function StageMonitor(props: JSX.IntrinsicElements["group"]) {
  const { nodes } = useGLTF(
    "/stagemonitor/models/scene.gltf",
  ) as unknown as GLTFResult;
  const [colorMap, mrMap, normalMap] = useTexture([
    "/stagemonitor/models/textures/lambert2_baseColor.png",
    "/stagemonitor/models/textures/lambert2_metallicRoughness.png",
    "/stagemonitor/models/textures/lambert2_normal.png",
  ]);

  useLayoutEffect(() => {
    [colorMap, mrMap, normalMap].forEach((t) => (t.flipY = false));
    colorMap.colorSpace = THREE.SRGBColorSpace;
  }, [colorMap, mrMap, normalMap]);

  return (
    <group {...props} dispose={null} scale={15}>
      {/* 1. Keep the outer group for your custom position/scale 
        2. Rotate the mesh directly to face the performers
      */}
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.monitor_speaker_lp_lambert2_0.geometry}
        /* ADJUST THESE THREE NUMBERS:
           X: Controls pitch (tilting up/down)
           Y: Controls yaw (turning left/right)
           Z: Controls roll
        */
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.05} // Adjusted scale to be more manageable
      >
        <meshStandardMaterial
          map={colorMap}
          normalMap={normalMap}
          metalnessMap={mrMap}
          roughnessMap={mrMap}
          metalness={1}
          roughness={1}
        />
      </mesh>
    </group>
  );
}
useGLTF.preload("/stagemonitor/models/scene.gltf");
