/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Professor E12^2 (https://sketchfab.com/profanity2009)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wall-speaker-482f1de1c44941b3b46358231e058c01
Title: Wall speaker
*/

import * as THREE from "three";
import { JSX } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh;
    Object_5: THREE.Mesh;
  };
  materials: {
    wallsupport: THREE.MeshPhysicalMaterial;
    wallspeaker: THREE.MeshPhysicalMaterial;
  };
};

export default function Subwoofer(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/subwoofer/models/scene.gltf",
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="speakersmd_0">
                <mesh
                  name="Object_4"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_4.geometry}
                  material={materials.wallsupport}
                />
                <mesh
                  name="Object_5"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_5.geometry}
                  material={materials.wallspeaker}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/subwoofer/models/scene.gltf");
